# Generated by Django 2.0.3 on 2018-12-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtab',
            name='review_data',
            field=models.CharField(max_length=5000),
        ),
    ]
